version: '3.8'

services:
  content-plan-generator:
    build: .
    ports:
      - "8080:8080"
    environment:
      - OLLAMA_API_URL=http://ollama:11434
      - PYTHONPATH=/app
    volumes:
      - .:/app
    command: bash -c "sleep 5 && python wizard/ui_builder.py"
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: always
    ports:
      - "11434:11434"
    networks:
      - ollama_network
    command: >
      sh -c "ollama pull llama2 && ollama serve"

networks:
  ollama_network:
    driver: bridge